name: my_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # mapbox_gl: ^0.16.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  sensors_plus: ^6.1.1
  flutter_compass: ^0.8.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  dartz: ^0.10.1
  location: ^8.0.0
  get_it: ^8.0.3
  email_validator: ^3.0.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  flutter_map_marker_popup: ^7.0.0
  cloudinary_public: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/location-arrow.svg
    - assets/db.json